name: MSYS2

on: push

jobs:
  msys2_ucrt64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          install: >-
            git
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-qt6-base
            mingw-w64-ucrt-x86_64-qt6-imageformats
            mingw-w64-ucrt-x86_64-qt6-multimedia
            mingw-w64-ucrt-x86_64-qt6-multimedia-wmf
            mingw-w64-ucrt-x86_64-qt6-pdf
            mingw-w64-ucrt-x86_64-qt6-svg
      - name: Build
        run: |
          export MSYSTEM=UCRT64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          cmake ../
          cmake --build . -j2
      - name: windeployqt
        run: |
          export MSYSTEM=UCRT64
          cd "$GITHUB_WORKSPACE"
          cd build/

          pwd
          ls -lah

          # prepare files for deployment
          windeployqt .

          # remove left-over build files
          rm -rf CMakeFiles cmake_install.cmake qt-commander_autogen .qt
          rm -f .ninja_deps .ninja_log build.ninja CMakeCache.txt
          ls -lah

          # copy possibly missing DLL files
          DLLS=$(find . -maxdepth 1 -type f -name '*.dll' | sort)
          for dll in $DLLS
          do
            echo "Copying dependencies for $dll ..."
            "$GITHUB_WORKSPACE"/ci/copy-dll-dependencies.sh "$dll" ./
          done

          # copy possibly missing DLL files for image format plugins
          "$GITHUB_WORKSPACE"/ci/copy-dll-dependencies.sh imageformats/qjp2.dll ./
          "$GITHUB_WORKSPACE"/ci/copy-dll-dependencies.sh imageformats/qjpeg.dll ./
          "$GITHUB_WORKSPACE"/ci/copy-dll-dependencies.sh imageformats/qmng.dll ./
          "$GITHUB_WORKSPACE"/ci/copy-dll-dependencies.sh imageformats/qtga.dll ./
          "$GITHUB_WORKSPACE"/ci/copy-dll-dependencies.sh imageformats/qtiff.dll ./
          "$GITHUB_WORKSPACE"/ci/copy-dll-dependencies.sh imageformats/qwebp.dll ./

          # copy license file + changelog
          cp "$GITHUB_WORKSPACE"/LICENSE ./
          cp "$GITHUB_WORKSPACE"/changelog.md ./

          VERSION=$(git describe --always)
          cd ..
          mv build qt-commander-${VERSION}

          # zip it
          '/c/Program Files/7-Zip/7z.exe' a -r qt-commander-windeployqt-${VERSION}.zip qt-commander-${VERSION}
      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: qt-commander-windows-msys2
          if-no-files-found: error
          archive: false
          path: |
            qt-commander*.zip
      - name: Create installer
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          export MSYSTEM=UCRT64
          cd "$GITHUB_WORKSPACE"

          VERSION=$(git describe --always)
          mv qt-commander-${VERSION} build
          "C:\Program Files (x86)\Inno Setup 6\iscc.exe" "setup\setup.iss"
          mv setup/Output/qt-commander-setup.exe qt-commander-setup_${VERSION}.exe
      - name: Upload installer
        uses: actions/upload-artifact@v7
        with:
          name: qt-commander-setup
          archive: false
          path: qt-commander-setup*.exe


#name: Release preparation

#on: push

#jobs:
  release_prep:
    needs: [msys2_ucrt64]
    runs-on: ubuntu-24.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          skip-decompress: true
      - name: List files
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -lah
          pwd
          ls -R
          pwd
          tree || echo "Looks like tree is not installed."
          DIRS=$(find "$(pwd)" -type d -name 'qt-commander*')
          for artifact_dir in $DIRS
          do
            cd "$artifact_dir"
            mv qt-commander* ../
            cd ..
            rmdir "$artifact_dir" || echo "Deletion of directory failed."
          done
          pwd
          ls -lah
          sha256sum qt-commander*.*
      - name: Generate release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            qt-commander*.*
          fail_on_unmatched_files: true
          body: changelog.md
          draft: true
          prerelease: true
          overwrite_files: false
          append_body: true
          name: 'Qt Commander vX.Y (2026-05-04) pre-release'
          tag_name: 'prerelease-test'
